name: ont-assembly-snake-homopolish
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - bioconda::homopolish==0.4.1
  - conda-forge::numpy==1.20.0
  - conda-forge::python==3.8.15

