name: ont-assembly-snake-homopolish
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - bioconda::homopolish==0.3.3
  - conda-forge::numpy==1.18.5
  - pandas==0.23.4
  - pyarrow==0.17.1
  - python==3.7.12
  - scikit-learn==0.21.3
  - scipy==1.7.3

